---
openio_oioproxy_sysconfig_dir: "/etc/oio/sds/{{ openio_oioproxy_namespace }}"
openio_oioproxy_servicename: "oioproxy-{{ openio_oioproxy_serviceid }}"

openio_oioproxy_definition_file: >
  "{{ openio_oioproxy_sysconfig_dir }}/
  {{ openio_oioproxy_servicename }}/{{ openio_oioproxy_servicename }}.conf"
...
