# roles/event_agent/tasks/main.yml
---
- name: "Include {{ ansible_distribution }} variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: install

- name: "Include {{ ansible_distribution }} tasks"
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: install

- name: Ensure directories exists
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner | default('openio') }}"
    group: "{{ item.group | default('openio') }}"
    mode: "{{ item.mode | default(0755) }}"
  with_items:
    - path: "{{ openio_event_agent_sysconfig_dir }}/{{ openio_event_agent_servicename }}"
    - path: "/var/log/oio/sds/{{ openio_event_agent_namespace }}/{{ openio_event_agent_servicename }}"
      owner: "{{ syslog_user }}"
      mode: "0750"
  tags: install

- name: Generate configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: openio
    group: openio
    mode: 0644
  with_items:
    - src: "event_agent.conf.j2"
      dest: "{{ openio_event_agent_sysconfig_dir }}/\
        {{ openio_event_agent_servicename }}/{{ openio_event_agent_servicename }}.conf"
    - src: "event_agent_handlers.conf.j2"
      dest: "{{ openio_event_agent_sysconfig_dir }}/\
        {{ openio_event_agent_servicename }}/oio-event-handlers.conf"
    - src: "service_event_agent.service.j2"
      dest: "/etc/systemd/system/openio-{{ openio_event_agent_servicename }}.service"
  register: _event_agent_conf

- name: restart event_agent
  systemd:
    daemon_reload: yes
    name: "openio-{{ openio_event_agent_servicename }}.service"
    state: restarted
    enabled: yes
  when:
    - _event_agent_conf.changed
    - not openio_event_agent_provision_only
  tags: configure
...
