# roles/rawx/defaults/main.yml
---
#openio_rawx_namespace: "OPENIO"

openio_rawx_bind_interface: "{{ ansible_default_ipv4.alias }}"
openio_rawx_bind_address:
  "{{ hostvars[inventory_hostname]['ansible_' + openio_rawx_bind_interface]['ipv4']['address'] }}"

# openio_rawx_serviceid: "0"
# openio_rawx_bind_port: 6200
# openio_rawx_volume: "{{ openio_data_mounts.mountpoint }}/{{ openio_rawx_namespace }}/{{ openio_rawx_servicename }}"

#openio_rawx_gridinit_file_prefix: ""

openio_rawx_golang: false

openio_rawx_pid_directory: "/run/rawx/{{ openio_rawx_namespace }}/{{ openio_rawx_servicename }}"
# MPM worker
openio_rawx_mpm_max_requests_per_child: 0
openio_rawx_mpm_max_spare_threads: 256
openio_rawx_mpm_min_spare_threads: 32
openio_rawx_mpm_server_limit: 16
openio_rawx_mpm_start_servers: 1
openio_rawx_mpm_threads_per_child: 256

openio_rawx_hash_width: 3
openio_rawx_hash_depth: 1
openio_rawx_fsync: enabled
openio_rawx_fsync_dir: enabled
openio_rawx_compression: "off"

openio_rawx_location: "{{ ansible_hostname }}.{{ openio_rawx_serviceid }}"
openio_rawx_location_ending: ""
openio_rawx_provision_only: false
...
