---
- name: POSTINSTALL - Generate inventory files
  hosts: add-node
  become: true
  any_errors_fatal: true
  vars:
    inventory:
      namespaces: {}
      created_at: "{{ ansible_date_time.iso8601_micro }}"

  pre_tasks:
    - name: Gathering network facts
      setup:
        gather_subset: network

    - name: Gathering needed facts
      setup:
        gather_subset: min
        filter: "{{ item }}"
      with_items:
        - ansible_distribution
        - ansible_os_family
        - ansible_date_time

  roles:
    # - role: namespace
    #   when: false
    - role: beanstalkd
      when: false
    # - role: conscienceagent
    #   when: false
    # - role: rawx
    #   when: false
    - role: oio-event-agent
      when: false
  tasks:
    # - include: inventory/namespace.yml
    # - include: inventory/rawx.yml
    # - include: inventory/conscienceagent.yml
    - include: inventory/beanstalkd.yml
    - include: inventory/oioeventagent.yml

    - name: Test directory namespace presence
      stat:
        path: "/etc/oio/sds/{{ namespace }}"
      register: _namespace_dir

    - name: Generate inventory
      copy:
        content: "---\n{{ inventory | to_nice_yaml }}\n...\n"
        dest: /etc/oio/sds/{{ namespace }}/inventory.yml
        owner: openio
        group: openio
        mode: 0640
      when: _namespace_dir.stat.exists
...
