---
- name: POSTINSTALL - Configure node for test
  hosts: oioswift
  become: true
  any_errors_fatal: true
  environment: "{{ openio_environment }}"

  pre_tasks:
    - name: Gathering network facts
      setup:
        gather_subset: network

    - name: Gathering needed facts
      setup:
        gather_subset: min
        filter: "{{ item }}"
      with_items:
        - ansible_distribution
        - ansible_os_family

    - name: set openio_bind_address as fact
      set_fact:
        openio_bind_address: "{{ openio_bind_address }}"

  tasks:
    - name: Install AWS client
      package:
        name: awscli

    - name: Install OpenStack client
      package:
        name: python-openstackclient
      ignore_errors: "{{ ansible_check_mode }}"

    - name: Get AWS credentials (Keystone)
      block:
        - name: Generate AWS credentials
          command: openstack ec2 credentials create -f json
          run_once: true
          register: cred
          environment:
            OS_PROJECT_DOMAIN_NAME: Default
            OS_USER_DOMAIN_NAME: Default
            OS_PROJECT_NAME: demo
            OS_USERNAME: demo
            OS_PASSWORD: "{{ openio_keystone_demo_password }}"
            OS_AUTH_URL: "http://{{ openio_bind_virtual_address }}:35357"
            OS_IDENTITY_API_VERSION: 3
            OS_IMAGE_API_VERSION: 2

        - name: Register AWS creds
          no_log: "{{ openio_no_log }}"
          ignore_errors: true
          register: aws_cred
          set_fact:
            access: "{{ (( cred.stdout | from_json ) | selectattr('Field', 'match', 'access') | list | first )['Value'] }}"
            secret: "{{ (( cred.stdout | from_json ) | selectattr('Field', 'match', 'secret') | list | first )['Value'] }}"

        - name: Register AWS creds round 2
          set_fact:
            access: "{{ ( cred.stdout | from_json )['access'] }}"
            secret: "{{ ( cred.stdout | from_json )['secret'] }}"
          when: aws_cred | failed
      when:
        - "'keystone' in groups"
        - groups['keystone'] | length > 0
      ignore_errors: "{{ ansible_check_mode }}"

    - name: Get AWS credentials (Tempauth)
      block:
        - name: Get user
          no_log: "{{ openio_no_log }}"
          set_fact:
            openio_oioswift_tempauth_user: "{{ openio_oioswift_filter_tempauth.keys() | select('match', 'user_.*') | list | first }}"
        - name: Get password of user
          no_log: "{{ openio_no_log }}"
          set_fact:
            openio_oioswift_tempauth_pass: "{{ openio_oioswift_filter_tempauth[openio_oioswift_tempauth_user].split(' ')[0] }}"
        - name: register AWS creds (Tempauth)
          no_log: "{{ openio_no_log }}"
          register: aws_cred
          set_fact:
            access: "{{ openio_oioswift_tempauth_user.split('_')[1:] | join(':') }}"
            secret: "{{ openio_oioswift_tempauth_pass }}"
          when:
            - "'keystone' not in groups or ('keystone' in groups and groups['keystone'] | length == 0)"
            - openio_oioswift_filter_tempauth | length > 1

      ignore_errors: "{{ ansible_check_mode }}"
      when: openio_oioswift_filter_tempauth is defined

    - name: Create .aws folder
      file:
        path: /root/.aws
        state: directory
        mode: 0750

    - name: Set aws credentials
      no_log: "{{ openio_no_log }}"
      copy:
        dest: /root/.aws/credentials
        content: |
          [default]
          aws_access_key_id = {{ access }}
          aws_secret_access_key = {{ secret }}
      ignore_errors: "{{ ansible_check_mode }}"

    - name: Configure environment for test
      copy:
        dest: "{{ item.path }}"
        content: "{{ item.content }}"
      with_items:
        - path: /root/.aws/config
          content: |
            [default]
            s3 =
               signature_version = s3v4
               max_concurrent_requests = 10
               max_queue_size = 100
               #multipart_threshold = 50MB
               #multipart_chunksize = 10MB
            region = {{ openio_s3_region }}

        - path: /etc/profile.d/openio.sh
          content: |
            export OIO_NS={{ namespace }}
            export OS_PROJECT_DOMAIN_NAME=Default
            export OS_USER_DOMAIN_NAME=Default
            export OS_PROJECT_NAME=demo
            export OS_IDENTITY_API_VERSION=3
            export OS_IMAGE_API_VERSION=2
      ignore_errors: "{{ ansible_check_mode }}"

    - name: Add script for tests in /root/checks.sh
      template:
        src: "{{ playbook_dir ~ '/../templates/checks.sh.j2' }}"
        dest: /root/checks.sh
        owner: root
        group: root
        mode: 0750
...
