# roles/blob_indexer/defaults/main.yml
---
#openio_blob_indexer_namespace: "OPENIO"
#openio_blob_indexer_serviceid: "0"

openio_blob_indexer_report_interval: 5
openio_blob_indexer_chunks_per_second: 2
openio_blob_indexer_interval: 300

#openio_blob_indexer_volume: "/var/lib/oio/sds/{{ openio_blob_indexer_namespace }}/{{ openio_blob_indexer_servicename }}"
openio_blob_indexer_provision_only: false
...
